"""i am updating the gaming session schema to have a player count

Revision ID: 493cefab6fd8
Revises: 2789291bca01
Create Date: 2026-09-21 03:46:09.040459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493cefab6fd8'
down_revision: Union[str, Sequence[str], None] = '2789291bca01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('player_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'player_count')
    # ### end Alembic commands ###
