"""add updated_at to friend groups

Revision ID: 8f2797540aad
Revises: 8a6ecbad9ef7
Create Date: 2026-09-21 05:27:24.346589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2797540aad'
down_revision: Union[str, Sequence[str], None] = '8a6ecbad9ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('unique_group_name_per_owner'), 'friend_groups', type_='unique')
    op.create_index(op.f('ix_friend_groups_owner_id'), 'friend_groups', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_friend_groups_owner_name', 'friend_groups', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_friend_groups_owner_name', 'friend_groups', type_='unique')
    op.drop_index(op.f('ix_friend_groups_owner_id'), table_name='friend_groups')
    op.create_unique_constraint(op.f('unique_group_name_per_owner'), 'friend_groups', ['owner_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('friend_groups', 'updated_at')
    # ### end Alembic commands ###
